### ISSUE TITLE
Use local sort-package-json, fall back to bundled

### ISSUE THREAD

**Issue by KingHenne** [unional/vscode-sort-package-json#1]
Something like https://github.com/prettier/prettier-vscode/blob/master/src/requirePkg.ts could be used to require `sort-package-json`, and thus support using a locally installed version instead of the bundled one. (Note that the aforementioned code also supports monorepos.)

Since the currently bundled version is outdated, the extension formats `package.json` files differently than a command line script that uses a locally installed version.

**Comment by unional** [comment]
Thank! I’ll find some time to do that. PR is welcome also. 🌷

**Comment by unional** [comment]
I have released a new version. Please see if it works or not.

Unfortunately, I didn't get the chance to write tests for this one.

**Comment by KingHenne** [comment]
Thanks, it works.
