### ISSUE TITLE
Sort on save

### ISSUE THREAD

**Issue by muuvmuuv** [unional/vscode-sort-package-json#2]
Would be nice, if it would sort on save

**Comment by unional** [comment]
Good idea. Should be pretty easy to do.

**Comment by llldar** [comment]
you could use it with "emeraldwalk.runonsave" and follwing config
```json
{
  "emeraldwalk.runonsave": {
    "commands": [
      {
        "match": "package.json",
        "isAsync": true,
        "cmd": "yarn sort-package-json ${file}"
      }
    ]
  },
}
```

**Comment by karlhorky** [comment]
I'm trying to get this working using [the `editor.codeActionsOnSave` built-in setting in VS Code](https://code.visualstudio.com/docs/languages/javascript#_code-actions-on-save), but this doesn't seem to work 🤔

`settings.json`

```json
{
  "editor.codeActionsOnSave": [
    // Sort package.json keys
    "editor.sortPackageJson"
  ]
}
```

([array value is also allowed](https://code.visualstudio.com/docs/languages/javascript#_code-actions-on-save:~:text=You%20can%20also%20set%20editor.codeActionsOnSave%20to%20an%20array%20of%20Code%20Actions%20to%20execute%20in%20order.))

**Comment by unional** [comment]
Yes. this feature has not been added to the extension yet.

> Maybe like this export class FormatActions implements vscode.CodeActionProvider { from this other extension here?

Yes, seems like that's the way to go: https://code.visualstudio.com/api/references/vscode-api#CodeActionProvider

The `DocumentFilter` used in `vscode.languages.registerCodeActionsProvider` can be `{ language: 'json', pattern: '**/package.json' }` (https://code.visualstudio.com/api/references/vscode-api#DocumentFilter)

Do you want to give it a stab?

**Comment by karlhorky** [comment]
@unional opened a PR at #68 - not sure whether this is correct / best practice like this though, I'm still pretty new to VS Code extension development

**Comment by karlhorky** [comment]
This works now in `unional.vscode-sort-package-json@1.4.3`, with the configuration below in your JSON settings:

```json
  "editor.codeActionsOnSave": [
    // Sort package.json keys
    "source.sortPackageJson"
  ],
```

Opened a PR for adding this to the readme:

- https://github.com/unional/vscode-sort-package-json/pull/75
