### ISSUE TITLE
Add URL to About section on GitHub

### ISSUE THREAD

**Issue by karlhorky** [unional/vscode-sort-package-json#63]
Hi there @unional, thanks for this package! 🙌 Very useful!

Currently, the About section on GitHub has no URL to get to [the Marketplace page for the extension](https://marketplace.visualstudio.com/items?itemName=unional.vscode-sort-package-json):

![Screenshot 2023-03-12 at 18 24 45](https://user-images.githubusercontent.com/1935696/224561643-2925f485-fe94-45a4-a53d-277058fc78a6.png)

Maybe you could add this link there?

**Comment by unional** [comment]
Hi @karlhorky thank you for the suggestion! 🕺 

The link is now added.

It's also added to the readme.

**Comment by karlhorky** [comment]
Glad to help, thanks for the updates!
